apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: auth0-ext
spec:
  hosts:
  - {YOUR_DOMAIN}
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {YOUR_DOMAIN}
spec:
  hosts:
  - {YOUR_DOMAIN}
  tls:
  - match:
    - port: 443
      sni_hosts:
      - {YOUR_DOMAIN}
    route:
    - destination:
        host: {YOUR_DOMAIN}
        port:
          number: 443
      weight: 100